### PR TITLE
[RFC] `create-backpack`

### PR DESCRIPTION
**Pull request by jaredpalmer**
This adds **`backpack init xxxx`** which bootstraps a new project with the following:
- [x] `src/index.js`
- [x] `package.json`
- [ ] `.gitignore`
- [ ] `README.md`
- [ ]  install dependencies

Outstanding Questions:
- `yarn` or `npm` by default? Not everyone has `yarn` installed yet.
- Should there be another special CLI package (that's meant to be globally installed once) that wraps this `init` script (which actually lives in `backpack-core` and would get versioned). Then users would never need to update the CLI package. This is how `create-react-app` works with `react-scripts`.
- What should the wrapper CLI's command be `create-backpack`, `create-backpack-app` (i don't like this), `backpack-setup`?

### CODE REVIEW

**Comment by BenDiuguid** [comment]
I love this idea!!

It's possible to feature detect `yarn` vs `npm`, `create-react-app` does it [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/create-react-app/index.js#L149).

I think it might make sense to have a globally installed CLI package, again similar to how the `create-react-app` project works, otherwise things like having projects that have `backpack` installed, and also having `backpack` installed globally could cause issues? (not sure what issues honestly)

As far as naming goes, I think `create-backpack-app` is a little long, I don't dislike it that much, I think it's clear. But we could yak shave the name for a while! 😄

**Comment by sompylasar** [comment]
`create-backpack-app` is not much longer than `create-react-app` and it aligns perfectly with `create-react-app` with regard to the purpose: to bootstrap/scaffold a ~~`react`~~ `backpack` app with no-to-little effort and configuration, though be able to `eject` when you need to customize.

**Comment by hawkins** [comment]
Worth mentioning that naming it `create-backpack-app` means it would support `yarn create` via `yarn create backpack-app my-app`. Although I suppose this would work with `create-backpack` as well, just without symmetry in how other `yarn create` commands are done

**Comment by aarohmankad** [comment]
Just contributing my opinions on the "Outstanding Questions":

* `yarn` by default, detecting it would probably be the way to go.
* A CLI tool for `backpack` would be great! While `create-backpack-app` is a little long, it does match `create-react-app` standard, and I feel this name would better relay it's purpose to developers.

Other than that, is there anything you need help with? I'm very enthused by the idea of a `create-react-app` for backends, and I'd like to help in any way possible.

**Comment by hawkins** [comment]
Hey @jaredpalmer , anything we could do to help get this ball rolling again? I, along with many others I'm sure, would be happy to help 😄

**Pull request closed without merging**
