### PR TITLE
Add example with docker/docker-compose

### LINKED ISSUE #43: Add docker example

### PR DESCRIPTION
**Pull request by posgarou**
Adds an example of using backpack with docker and docker-compose.

Closes #43 .

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Thanks for this. Would you mind reworking the Dockerfiles to use `mhart/alpine-node:base` instead of `node`? `node` is a huge docker image, and we don't need the whole thing.

**Comment by aslafy-z** [comment]
Why mhart/alpine-node over node:alpine ?

**Comment by jaredpalmer** [comment]
just what we use internally, but node:alpine is probably fine.

**Comment by posgarou** [comment]
Thanks for the feedback, and sorry for the delay getting back to you.

I considered using `node:alpine` (or `mhart/alpine-node`), but ended up going with the vanilla image (`FROM node`) for two reasons:

1. For an example like this, it seemed best to go with the default official image, other things being equal, and `node` is the default (for good or ill).
2. The Dockerfile would need to install dependencies for node-gyp (since backpack uses native modules), which would slow down the build.  In other words, you'd save time and bandwidth on the download, but lose a lot of time on the build process.

If neither of those reasons seems convincing, I'm happy to switch it over to alpine—just let me know.

**Comment by zefexdeveloper** [comment]
What is the reason this got closed? It would be nice to have a docker example

**Pull request closed without merging**
