### PR TITLE
Fix and migration for yarn-workspaces

### PR DESCRIPTION
**Pull request by JacopKane**
Focusing on fixing errors occurring when using this module within a monorepo at the build time.
Also implements workspaces to this repo which dramatically speeds up the build time without any error.

This PR is compatible with `v0.5.0`, `babel 6` version. I would suggest moving `master` into a `next` branch and publish this as `master` with a minor version like `v0.6.0` since it's backwards compatible.

- Fix webpack and migrate repo for yarn-workspaces
- Upgrade webpack and it's dependencies
- Update .gitignore
- Add package-scripts
- Upgrade Lerna

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Can you resolve the conflicts?

**Comment by JacopKane** [comment]
@jaredpalmer For sure I can but I didn't on purpose because right now `master` branch is not backwards compatible due to the previous PR that you merged which I created for Babel 7.

Babel 7 might create many issues (in our case it does at our company due to some old presets for example) and I strongly suggest move `master` into a `beta/next` branch and merge this with a new `master` from `v5.0.0`

If you still want to keep `master` as is then you can close this pull request and use this one instead:
https://github.com/jaredpalmer/backpack/pull/114

I can also help if you'll give me permission to do so.

**Comment by jaredpalmer** [comment]
That makes sense

**Comment by jaredpalmer** [comment]
Made you a collaborator. If you can move master to next, and merge this with a new master from v5. That would be great

**Comment by JacopKane** [comment]
Cool, I'll be able to do it probably tomorrow or tonight

**Pull request merged**
